language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build design_huddle_admin.gemspec
  - gem install ./design_huddle_admin-1.0.0.gem
