=begin
#Admin API

#The Admin API represents all functionality that a Design Huddle client administrator may perform. Most API methods do not require a specific user context and can be accessed using an App Access Token for authorization, but some methods must run on behalf of a specific user and therefore must use a User Access Token. The most common integration use cases consist of template management/synchronization and updating/approving/exporting user-created design projects. Read more about authentication <a target=\"_parent\" href=\"https://api.designhuddle.com#authentication\">here</a> and embedding the Design Huddle editor <a target=\"_parent\" href=\"https://api.designhuddle.com#embedding\">here</a>.

The version of the OpenAPI document: 2023-02-02T22:12:58Z
Contact: support@designhuddle.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DesignHuddleAdmin::ExportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExportApi' do
  before do
    # run before each test
    @api_instance = DesignHuddleAdmin::ExportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExportApi' do
    it 'should create an instance of ExportApi' do
      expect(@api_instance).to be_instance_of(DesignHuddleAdmin::ExportApi)
    end
  end

  # unit tests for projects_project_id_export_jobs_job_id_get
  # Retrieve export job progress
  # @param job_id 
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ProjectsProjectIDExportJobsJobIDGETSuccess]
  describe 'projects_project_id_export_jobs_job_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_export_post
  # Create an export job
  # @param project_id 
  # @param projects_project_id_export_post_request 
  # @param [Hash] opts the optional parameters
  # @return [ProjectsProjectIDExportPOSTSuccess]
  describe 'projects_project_id_export_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
