=begin
#Admin API

#The Admin API represents all functionality that a Design Huddle client administrator may perform. Most API methods do not require a specific user context and can be accessed using an App Access Token for authorization, but some methods must run on behalf of a specific user and therefore must use a User Access Token. The most common integration use cases consist of template management/synchronization and updating/approving/exporting user-created design projects. Read more about authentication <a target=\"_parent\" href=\"https://api.designhuddle.com#authentication\">here</a> and embedding the Design Huddle editor <a target=\"_parent\" href=\"https://api.designhuddle.com#embedding\">here</a>.

The version of the OpenAPI document: 2023-02-02T22:12:58Z
Contact: support@designhuddle.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DesignHuddleAdmin::TemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TemplatesApi' do
  before do
    # run before each test
    @api_instance = DesignHuddleAdmin::TemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemplatesApi' do
    it 'should create an instance of TemplatesApi' do
      expect(@api_instance).to be_instance_of(DesignHuddleAdmin::TemplatesApi)
    end
  end

  # unit tests for template_customization_objects_post
  # Create a template customization object
  # @param template_customization_objects_post_request 
  # @param [Hash] opts the optional parameters
  # @return [TemplateCustomizationObjectsPOSTSuccess]
  describe 'template_customization_objects_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for template_jobs_job_id_get
  # Retrieve template publish progress
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [TemplateJobsJobIDGETSuccess]
  describe 'template_jobs_job_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for templates_get
  # List templates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :brand_id Specify the Brand ID to filter the result by.
  # @option opts [String] :brand_code Specify the Brand Code to filter the result by.
  # @option opts [String] :media_type Specify the media type to filter the result by.
  # @option opts [Array<String>] :media_types Specify the media types to filter the result by.
  # @option opts [String] :template_status Specify the template status to filter the result by.
  # @option opts [Array<String>] :template_statuses Specify the template statuses to filter the result by.
  # @option opts [Integer] :primary_template_category_item_id Specify the Primary Template Category Item ID to filter the result by.
  # @option opts [Array<Integer>] :primary_template_category_item_ids Specify the Primary Template Category Item IDs to filter the result by.
  # @option opts [String] :source_project_id Specify the Source Project ID to filter the result by.
  # @option opts [Array<String>] :source_project_ids Specify the Source Project IDs to filter the result by.
  # @option opts [Integer] :width Specify the width to filter the result by.
  # @option opts [Integer] :height Specify the height to filter the result by.
  # @option opts [String] :unit_type Specify the unit type to filter the result by.
  # @option opts [String] :search A search term used to narrow the focus of the result.
  # @option opts [String] :sort Specify which attribute to order the result by.
  # @option opts [String] :order Specify whether the result should be retrieved in ascending or descending order.
  # @option opts [Integer] :limit Specify the number of items per page to return.
  # @option opts [Integer] :page Specify which page of the result to return.
  # @option opts [Array<String>] :fields Specify the fields to the retrieve.
  # @return [TemplatesGETSuccess]
  describe 'templates_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for templates_post
  # Publish a template
  # @param templates_post_request 
  # @param [Hash] opts the optional parameters
  # @return [TemplatesPOSTSuccess]
  describe 'templates_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for templates_template_id_template_code_delete
  # Archive a template
  # @param template_id_template_code 
  # @param [Hash] opts the optional parameters
  # @return [TemplatesTemplateIDBaseSuccess]
  describe 'templates_template_id_template_code_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for templates_template_id_template_code_get
  # Retrieve a template
  # @param template_id_template_code 
  # @param [Hash] opts the optional parameters
  # @return [TemplatesTemplateIDGETSuccess]
  describe 'templates_template_id_template_code_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for templates_template_id_template_code_patch
  # Update a template
  # @param template_id_template_code 
  # @param templates_template_idpatch_request 
  # @param [Hash] opts the optional parameters
  # @return [TemplatesTemplateIDBaseSuccess]
  describe 'templates_template_id_template_code_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for templates_template_id_template_code_put
  # Upsert a template
  # @param template_id_template_code 
  # @param templates_template_idput_request 
  # @param [Hash] opts the optional parameters
  # @return [TemplatesTemplateIDBaseSuccess]
  describe 'templates_template_id_template_code_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
