=begin
#Admin API

#The Admin API represents all functionality that a Design Huddle client administrator may perform. Most API methods do not require a specific user context and can be accessed using an App Access Token for authorization, but some methods must run on behalf of a specific user and therefore must use a User Access Token. The most common integration use cases consist of template management/synchronization and updating/approving/exporting user-created design projects. Read more about authentication <a target=\"_parent\" href=\"https://api.designhuddle.com#authentication\">here</a> and embedding the Design Huddle editor <a target=\"_parent\" href=\"https://api.designhuddle.com#embedding\">here</a>.

The version of the OpenAPI document: 2023-02-02T22:12:58Z
Contact: support@designhuddle.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

# Common files
require 'design_huddle_admin/api_client'
require 'design_huddle_admin/api_error'
require 'design_huddle_admin/version'
require 'design_huddle_admin/configuration'

# Models
require 'design_huddle_admin/models/base_create_success'
require 'design_huddle_admin/models/base_error'
require 'design_huddle_admin/models/base_success'
require 'design_huddle_admin/models/brand'
require 'design_huddle_admin/models/dimensions'
require 'design_huddle_admin/models/list_success'
require 'design_huddle_admin/models/media_type'
require 'design_huddle_admin/models/page'
require 'design_huddle_admin/models/page_scene_slides_inner'
require 'design_huddle_admin/models/project_approval_log'
require 'design_huddle_admin/models/project_approval_status'
require 'design_huddle_admin/models/project_status'
require 'design_huddle_admin/models/projects_get_success'
require 'design_huddle_admin/models/projects_post_request'
require 'design_huddle_admin/models/projects_post_request_one_of'
require 'design_huddle_admin/models/projects_post_request_one_of1'
require 'design_huddle_admin/models/projects_post_request_one_of2'
require 'design_huddle_admin/models/projects_post_request_one_of3'
require 'design_huddle_admin/models/projects_post_request_one_of3_dimensions'
require 'design_huddle_admin/models/projects_post_request_one_of4'
require 'design_huddle_admin/models/projects_post_request_one_of5'
require 'design_huddle_admin/models/projects_post_request_one_of6'
require 'design_huddle_admin/models/projects_post_request_one_of7'
require 'design_huddle_admin/models/projects_post_request_one_of7_dimensions'
require 'design_huddle_admin/models/projects_post_success'
require 'design_huddle_admin/models/projects_project_id_error403'
require 'design_huddle_admin/models/projects_project_id_error404'
require 'design_huddle_admin/models/projects_project_id_export_jobs_job_id_error403'
require 'design_huddle_admin/models/projects_project_id_export_jobs_job_idget_success'
require 'design_huddle_admin/models/projects_project_id_export_jobs_job_idget_success_one_of'
require 'design_huddle_admin/models/projects_project_id_export_jobs_job_idget_success_one_of1'
require 'design_huddle_admin/models/projects_project_id_export_jobs_job_idget_success_one_of1_data'
require 'design_huddle_admin/models/projects_project_id_export_jobs_job_idget_success_one_of_data'
require 'design_huddle_admin/models/projects_project_id_export_post_request'
require 'design_huddle_admin/models/projects_project_id_export_post_request_one_of'
require 'design_huddle_admin/models/projects_project_id_export_post_request_one_of1'
require 'design_huddle_admin/models/projects_project_id_export_post_request_one_of1_bleed'
require 'design_huddle_admin/models/projects_project_id_export_post_request_one_of1_bleed_margin'
require 'design_huddle_admin/models/projects_project_id_export_post_request_one_of2'
require 'design_huddle_admin/models/projects_project_id_export_post_request_one_of3'
require 'design_huddle_admin/models/projects_project_id_export_post_request_one_of4'
require 'design_huddle_admin/models/projects_project_id_export_post_success'
require 'design_huddle_admin/models/projects_project_idget_success'
require 'design_huddle_admin/models/projects_project_idpatch_request'
require 'design_huddle_admin/models/scene'
require 'design_huddle_admin/models/scene_scene_slides_inner'
require 'design_huddle_admin/models/template_customization_objects_post_request'
require 'design_huddle_admin/models/template_customization_objects_post_success'
require 'design_huddle_admin/models/template_jobs_job_id_error403'
require 'design_huddle_admin/models/template_jobs_job_idget_success'
require 'design_huddle_admin/models/template_jobs_job_idget_success_one_of'
require 'design_huddle_admin/models/template_jobs_job_idget_success_one_of_data'
require 'design_huddle_admin/models/template_status'
require 'design_huddle_admin/models/templates_get_success'
require 'design_huddle_admin/models/templates_post_request'
require 'design_huddle_admin/models/templates_post_success'
require 'design_huddle_admin/models/templates_template_id_base_success'
require 'design_huddle_admin/models/templates_template_id_base_success_one_of'
require 'design_huddle_admin/models/templates_template_id_base_success_one_of_data'
require 'design_huddle_admin/models/templates_template_id_error404'
require 'design_huddle_admin/models/templates_template_idget_success'
require 'design_huddle_admin/models/templates_template_idpatch_request'
require 'design_huddle_admin/models/templates_template_idput_request'
require 'design_huddle_admin/models/templates_template_id_template_code_delete_template_id_template_code_parameter'
require 'design_huddle_admin/models/unit_type'
require 'design_huddle_admin/models/user_group'
require 'design_huddle_admin/models/user_groups_match_type'

# APIs
require 'design_huddle_admin/api/export_api'
require 'design_huddle_admin/api/projects_api'
require 'design_huddle_admin/api/templates_api'

module DesignHuddleAdmin
  class << self
    # Customize default settings for the SDK using block.
    #   DesignHuddleAdmin.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
